# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction.

What are the prerequisites, for both knowledge and e.g. software setup?

A user completing the task would want to have basic RStudio knowledge in addition to having RStudio installed on their computer. Having the creditmodel package installed will be necessary. and having some machine learning and statistics knowledge will be helpful but not necessary.

What are the basic requirements for any data that the method is used on? 
- Are missing values allowed? 
They are not encouraged, but they are allowed because there are functions within the creditmodel package that handle datasets with missing values.
- Should the data be confined within a certain range? 
data on credit scores should be limited to a range of 300-850 and yearly income amounts should be reasonable.
- Does the data have to be approximately normally distributed?
No

What are the basic components of the task? - Outline these in a bit more detail

The basic components of the task are to load in a dataset of information from prior loans, use functions within the creditmodel package to preprocess the data to prepare it for model training, train a regression model for loan approval/denial predictions based on that dataset, and then apply the model to make predictions on new loan applicant data.

What decisions does the user need to be prepared to make on the fly?
They should be prepared to handle missing values in the prior loan dataset in case they appear.

What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?

## Additional Guidance

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic).

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. This document should remain as an appendix to your main report.
